version: '3.9'

# █▄░█ █▀▀ ▀█▀ █░█░█ █▀█ █▀█ █▄▀ █▀
# █░▀█ ██▄ ░█░ ▀▄▀▄▀ █▄█ █▀▄ █░█ ▄█

networks:
  webgest_net:
    driver: bridge

services:
  webgest: 
    build: 
      context: .
    ports: 
      - 80
    networks:
      - webgest_net