version: '3.7'

networks:
  webgest_net:
    driver: bridge

services:
  webgest: 
    image: imatto/webgest:latest-serverino
    restart: unless-stopped # dev only
    ports: 
      - 80
    networks:
      - webgest_net
