version: '3.9'

networks:
  webtrax_net:
    driver: bridge

services:
  webtrax: 
    image: imatto/webgest:latest-serverino
    restart: unless-stopped # dev only
    ports: 
      - 80
    networks:
      - webtrax_net
