# syntax=docker/dockerfile:1

FROM node:latest

RUN mkdir /webgest_cnt && chown node:node /webgest_cnt
RUN mkdir /webgest_cnt/node_modules && chown node:node /webgest_cnt

WORKDIR /webgest_cnt

COPY --chown=node:node ./package.json ./package-lock.json ./

RUN npm ci --quiet

COPY --chown=node:node ./ .

ENTRYPOINT [ "npm", "start"]
